### ISSUE TITLE
[1.18.1 Forge] Quark Oddities affects Enchanting Table Trinket reroll.

### ISSUE THREAD

**Issue by Baggytrousers27** [Cozary/Issue-Tracker#10]
Forge 1.18.1 39.0.10
curios-forge-1.18.1-5.0.4.2
Nameless+Trinkets-1.18.1-1.3.1
AutoRegLib-1.7-52
Quark-3.0-334
QuarkOddities-1.18

Oddities overwrites the vanilla Enchanting table (especially the gui) meaning trinkets cannot be rerolled easily.

**Comment by Cozary** [comment]
That's bad, I'll have to do a check to see if Quark is there and get it to work with his enchantment table.

**Comment by Cozary** [comment]
Breaking the Trinkets with Quark should now work.
