### ISSUE TITLE
Crash potentially caused by Nelumbo Trinket.

### ISSUE THREAD

**Issue by MsVoxxie** [Cozary/Issue-Tracker#11]
Mod: Nameless Trinkets
Version: Minecraft: 1.18.1 - Mod: 1.3.2
Bug explanation: A User on my server seemingly while walking through a Savannah biome randomly gets disconnected and was unable to log back in until teleported elsewhere. After they removed the trinket, the issue had gone away after attempting to reproduce it. 
Bug image: None
Code: [Crash Report (ServerSide)](https://www.toptal.com/developers/hastebin/picuhayotu.rb)

Thanks in advance for peeking at this.

[Pack Mod list](https://share.voxxie.me/Viewer/../i/2022-01-16_01.45.14.html)

**Comment by Cozary** [comment]
I see, it seems to be a problem with my mod. At the moment do not use Nelumbo or Dark Nelumbo as they work the same. I'll try to fix it as soon as I can. I'm sorry for the problems.

**Comment by MsVoxxie** [comment]
> I see, it seems to be a problem with my mod. At the moment do not use Nelumbo or Dark Nelumbo as they work the same. I'll try to fix it as soon as I can. I'm sorry for the problems.

Awesome, I'm glad I was able to bring it to attention and no worries,! It was a relatively easy fix :)

**Comment by Cozary** [comment]
The bug is fixed. I'll close the issue when I upload the update to Curseforge.

**Comment by MsVoxxie** [comment]
Appreciate it greatly!

**Comment by Cozary** [comment]
The new version will appear soon on Curseforge. ^^
