### ISSUE TITLE
Crash when placing tinted campfires

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Cozary/Issue-Tracker#12]
Mod: Tinted campfires 1.1.3
Minecraft version: 1.18.1
Forge version: 39.0.79

Latest.log file: https://gist.github.com/TheDeviantCrafter/dc5594c6e90f5408b510610a9d7676fa
Crash log: https://gist.github.com/TheDeviantCrafter/11c7a58a93774536c99a5958792ed7e5

The crash occured immediately upon placing a pink tinted campfire.

Feature NBT Deadlock Be Gone is in the pack. Not sure if it's related, but it's an NBT crash so maybe.

**Comment by Cozary** [comment]
It may be because Tinted Campfire is built with Forge 39.0.44. I'll update it and it should fix itself.

**Comment by Cozary** [comment]
A new version has been uploaded to Curseforge. The problem should be solved. Sorry for the delay.
