### ISSUE TITLE
Suggestion: Tint campfires with dispensers

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Cozary/Issue-Tracker#13]
Point a dispenser at a campfire, insert dye, apply redstone signal, *poof*.

This could be used to create some fancy light shows, or automatically change the color of campfires at night for example.

**Comment by Cozary** [comment]
It's a good idea, I'll see if I can implement it.

**Comment by Cozary** [comment]
It has been implemented in the new version. ^^
