### ISSUE TITLE
[1.18] Nameless trinket Missing item name

### ISSUE THREAD

**Issue by ffuentesm** [Cozary/Issue-Tracker#14]
Mod: Nameless Trinkets 
Version: Nameless Trinkets-1.18.1-1.4.1.jar
Bug explanation: Item has a missing name
Bug image:
![image](https://user-images.githubusercontent.com/44974827/156098186-8868c1e8-3419-42cf-b180-e8d768fae2d7.png)

**Comment by Cozary** [comment]
I'll fix it as soon as I can.

**Comment by Cozary** [comment]
Fixed
