### ISSUE TITLE
Trinkets Requiring Expandability 

### ISSUE THREAD

**Issue by Darkosto** [Cozary/Issue-Tracker#16]
Hello!

Is it possible to setup a conditional to disable trinkets when the Expandability mod is not installed? Currently, the trinkets are injected to loot tables regardless of whether or not you have the extra mods. If you're unable to setup a condition, then maybe disabling the items might be a good idea, too?

In cases of json recipes you can generally use this to setup a condition:
```json
{ "modid": "mekanism", "type": "forge:mod_loaded" }
```

Not sure if this will work on your json configs or loot tables, but hopefully it helps either way.

Thanks so much and I appreciate your work on this mod!
Darkosto

**Comment by Cozary** [comment]
You can always destroy items to make new ones or  you can also make them not appear in the loot tables [chest] in the configuration., but maybe making them conditional is a good idea. I'll see what I do.

**Comment by Cozary** [comment]
Done ^^
