### ISSUE TITLE
Journeymap cannot find Entity_icon

### ISSUE THREAD

**Issue by revdave33** [Cozary/Issue-Tracker#17]
Forge: 4.0.32 (MC 1.18.2)
Ore Creeper: 1.18.2-1.1.7
Journeymap: 1.18.2-5.8.0

When looking at the Journeymap map, the ore creepers all show up as the unknown entity icon. It would be nice to be able to see which ore creeper I want to move toward from the map.

In looking at the logs, I see this line...
[Render thread/WARN]: Image not found: ore_creeper:textures/entity_icon/copper_creeper.png
[Render thread/WARN]: Image not found: ore_creeper:textures/entity_icon/iron_creeper.png

**Comment by Cozary** [comment]
Yes, it would be cool if the icons appear. I didn't know about them so I'll add it.

**Comment by Cozary** [comment]
I already added the mob icons. ^^
At some point the latest version will appear on curseforge.
