### ISSUE TITLE
[1.18.2] Missing curios slots

### ISSUE THREAD

**Issue by ffuentesm** [Cozary/Issue-Tracker#19]
version: Nameless Trinkets-1.18.2-1.5.2.jar
curios-forge-1.18.2-5.0.7.0.jar
Forge: 40.1.0
Minecraft: 1.18.2

Most Trinkets has no curios slots
![image](https://user-images.githubusercontent.com/44974827/164880236-f24a90e3-e449-4b2b-bc08-e4543a036e05.png)
![image](https://user-images.githubusercontent.com/44974827/164880681-ce2de4ff-7b44-43d2-9689-4f5395f957d6.png)
![image](https://user-images.githubusercontent.com/44974827/164880727-1665043f-728c-497e-8784-1b78b628157f.png)

**Comment by Cozary** [comment]
Weird, it might have happened when upgrading everything to 1.18.2.

**Comment by Cozary** [comment]
It was a problem with the tags, it's fixed now.

**Comment by Raycoms** [comment]
Will 1.18.1 also get this fix?

**Comment by Cozary** [comment]
I totally forgot to do it for 1.18.1, sorry. I will try to fix it as soon as possible.
