### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by LadyMisitu** [Cozary/Issue-Tracker#2]
Mod: Floral Enchantment
Version: 1.17.1 
Bug explanation: When I try to start the game it takes me to the Mojang load screen, freeze for a moment, and pops a message
about an error occurring during the common_setup event phase, I try erasing the mod and downloading it again, but it doesn't help
Bug image:
![image](https://user-images.githubusercontent.com/84095223/131723415-2ab40be6-a9ac-4641-a1bd-cbfe162db95d.png)

**Comment by Cozary** [comment]
It seems that certain things have changed in more recent versions of Forge 1.17. I will update the mod to the latest version.

**Comment by LadyMisitu** [comment]
okay! could you notify me when the new version is available?

**Comment by Cozary** [comment]
The new version is now available.  ^^
