### ISSUE TITLE
Ticking Player 1.16.5

### ISSUE THREAD

**Issue by BigBillsHell** [Cozary/Issue-Tracker#20]
Mod: Nameless Trinkets
Version: 1.16.5
Bug Explanation:
When using items from the Blue Skies mod, like one of the spell books from the boss, and attempting to shoot someone with it, it crashes the game and prompts a ticking player crash.
![image](https://user-images.githubusercontent.com/93220380/164950100-686e1df5-0aaa-484f-8b68-a5fd882c947f.png)

Code: https://www.toptal.com/developers/hastebin/cigomitibe.rb

**Comment by Cozary** [comment]
It appears to be caused by the Creeper Sense trinket. I don't support old versions, but I'll try to make a quick fix. At least fix it so it doesn't crash.

**Comment by Cozary** [comment]
Wait, I just saw it. Why are you using Nameless Trinkets v1.0.1? The latest version is v1.1.2 at 1.16.5. Update the mod first, and then if the problem persists open another support ticket again. I hope the problem doesn't persist. ^^
