### ISSUE TITLE
[1.18.2] Curious slot items dropping in death

### ISSUE THREAD

**Issue by ffuentesm** [Cozary/Issue-Tracker#21]
I am not sure what changed, but in the previous version of the mod, the curious slots items would stay there in death. 

version: Nameless Trinkets-1.18.2-1.5.3.jar
curios-forge-1.18.2-5.0.7.0.jar
Forge: 40.1.0
Minecraft: 1.18.2

**Comment by Cozary** [comment]
It had to be something with Curios, but the items shouldn't be in your inventory when you die. Lucky it fixed itself.
