### ISSUE TITLE
Blue Skies Problems with Latest version in 1.16.5

### ISSUE THREAD

**Issue by BigBillsHell** [Cozary/Issue-Tracker#22]
Mod: Nameless Trinkets 1.16.5 latest version
Version: 1.1.2
Bug Explanation: using the spellbook item in Blue Skies stops everything in the world
Bug Video: https://streamable.com/1o0qlx
Code: Latest Log: https://www.toptal.com/developers/hastebin/epivicokib.yaml

**Comment by Cozary** [comment]
Most likely it is the capabilities that are causing the problem. In 1.16.x it was the first time I used them, and although in current versions they are fine in the code, in 1.16.x they are slightly poorly implemented. I'm sorry you ran into a problem but I can't redo all the capabilities in 1.16, sorry.
