### ISSUE TITLE
[1.18.2] Crash when the "bonemeal" trinket is active

### ISSUE THREAD

**Issue by ffuentesm** [Cozary/Issue-Tracker#23]
Mod Version: Nameless Trinkets-1.18.2-1.5.3.jar
Bug explanation: When I equip the trinket the bonemeals the area around me, the game crashes.
[crash-2022-05-06_14.01.09-server.txt](https://github.com/Cozary/Issue-Tracker/files/8642637/crash-2022-05-06_14.01.09-server.txt)

https://pastebin.com/zCtE05a5

**Comment by Cozary** [comment]
It should already be fixed.
