### ISSUE TITLE
[Suggestion] Ore Creepers - Compatiblity with Ore Mods

### ISSUE THREAD

**Issue by Answordy** [Cozary/Issue-Tracker#24]
I would like to make a suggestion for the Ore Creepers mod.
Add support for mods that add new stone variants to existing vanilla ores.
Like: More Ore Stones, Unearthed, Excavated Variants

_To clarify, I'm not suggesting support for other mods that add ores (like Ruby, Sapphire ect.) It has been suggested several times already, and there are endless amounts of those kind of mods. 
What I suggest is probably easier to make, since there are only a few mods like this, some of them are very popular, and they only add a couple of ore variants, also it doesn't require the creation of new creepers. 
My suggestion is to make creepers transform not just stone into ores, but granite, diorite etc. when the mods I mentioned are installed. I feel like this issue is mostly a cosmetic thing, but in some cases especially with Unearthed it is more like a more serious incompatiblity, since that mod replaces stone 80% of the time with other varaints like Slate, Mudstone, etc. So creepers basically are doing nothing._

![2022-07-03_09 18 07](https://user-images.githubusercontent.com/82783515/177029450-653120c6-28e0-4475-b017-2446a3e5173d.png)

**Comment by Cozary** [comment]
Good idea, will be implemented in the near future.

**Comment by Cozary** [comment]
![image](https://user-images.githubusercontent.com/69899934/181523516-00ae8a2d-5405-441f-af6e-4575ab1abd49.png)
Working on it

**Comment by Cozary** [comment]
Added compatibility with the following mods:

-More Ore Stones
-Unearthed
-Excavated Variants

If you find any problem let me know ^^
