### ISSUE TITLE
[Suggestion - Nameless Trinkets] Backport The Ability To Have More Trinket Slots to 1.16.5

### ISSUE THREAD

**Issue by PhweeDev** [Cozary/Issue-Tracker#26]
I feel it's important for 1.16.5, being a major modding version to have the ability to have more than one single trinket slot.

**Comment by Cozary** [comment]
I think having new trinkets used some Curios code that was +1.17, but I can't remember. I'm going to look at it, and if it can be done, I'll add it.

**Comment by Cozary** [comment]
Done. The extra slots of the new versions have been added as well as the Mysterious Trinket to obtain more Trinket Slots.

**Comment by PhweeDev** [comment]
Thank you!
