### ISSUE TITLE
[No More Advancements] Recipe advancements are not blocked

### ISSUE THREAD

**Issue by jamesjimmy88** [Cozary/Issue-Tracker#27]
As per title, the recipe advancements are still getting loaded. The advancements blocking is working fine.
Tested with NoMoreAdvancements 1.0.0 on forge version 40.1.68.

Log https://pastebin.com/NnMhu7dZ

**Comment by Cozary** [comment]
The mod is compiled on Forge 40.1.0. That may be why it's not working properly. I will update it.

**Comment by Cozary** [comment]
I don't see an easy way to fix that part. I recommend you play on the recommended version of Forge. Besides, the mod will not receive any more updates.

**Comment by jamesjimmy88** [comment]
Unfortunately I can't do that because of other mods.
Still, I appreciate the attempt. Thank you.
