### ISSUE TITLE
[sugestion - Nameless Trinkets] Change trinket spawn chance config

### ISSUE THREAD

**Issue by EnderMelody** [Cozary/Issue-Tracker#28]
The way the current spawn chance for trinkets is handled is somewhat confusing and hard to use. Are the chances added together and then divided for an overall chance or is each trinket rolled till one spawns? The way the config is divided per trinket makes it hard to get an overall estimate of the spawn chances as well.
Would it be possible to instead give each trinket a weight and use a separate % that determines the chance of a trinket generating at all, as this would make it easier to balance the spawn chance for trinkets overall as well as individually.

**Comment by Cozary** [comment]
The current trinket spawn chance works as follows: The game selects the full list of trinkets, picks a trinket at random and attempts to spawn in the chest. I have no current intention to change it, sorry.

**Comment by EnderMelody** [comment]
its no problem, i mainly just wanted to know how the current system works, thanks for the explanation
