### ISSUE TITLE
[Bug] Rage Mind don't work ?

### ISSUE THREAD

**Issue by Traktool** [Cozary/Issue-Tracker#30]
I've the Rage Mind equipped, I've taken many many many damages, but nothing increase
Is it bugged ?

Minecraft 1.18.2
Forge 40.1.73
Nameless Artifact 1.5.8

**Comment by Cozary** [comment]
Does the increased damage stay 0 at all times? Even after leaving and entering the world?

**Comment by Traktool** [comment]
> Does the increased damage stay 0 at all times? Even after leaving and entering the world?

I can change world, reconnect or esle, nothing happened, increase damage is still 0

**Comment by Cozary** [comment]
It may be the Forge version, the mod is in 40.1.0

**Comment by Cozary** [comment]
Maybe I'll release a version for the latest version of forge. usually what I do is stick with the recommended version.
