### ISSUE TITLE
Broken Magnet (and presumably other things) applies in spectator

### ISSUE THREAD

**Issue by Xetaxheb** [Cozary/Issue-Tracker#31]
As funny as it is for a pile of items to follow me around, equipped trinkets probably shouldn't be active if the player is in spectator, for various reasons.

**Comment by Cozary** [comment]
Well, they were never meant to be used in Spectator Mode. So all the ones that can work will work. In v1.6.1 there will be a fix to prevent this from happening.

**Comment by Cozary** [comment]
Done
