### ISSUE TITLE
OreCreeper only spawns CoalCreepers

### ISSUE THREAD

**Issue by revdave33** [Cozary/Issue-Tracker#32]
Mod: Ore+Creeper-1.19.1-1.1.9
Forge: 43.1.25
Minecraft: 1.19.2

The only OreCreeper that is spawned is Coal. I even zeroed out the weight of the CoalCreeper being spawned and they are still the only ones.

**Comment by Cozary** [comment]
You are using a beta version of Ore Creeper for 1.19.1 on 1.19.2 with the latest version of Forge. Obviously it will bring some problems. I haven't had much time lately. I plan to update it soon, everything will be fixed there.
