### ISSUE TITLE
[1.18.2] Ethereal Wings Trinket permanently sets flight speed

### ISSUE THREAD

**Issue by Saereth** [Cozary/Issue-Tracker#33]
Taking off ethereal wings does not return your flight speed values to normal, you maintain the same slow speed that the wings grant, even in creative

Steps to reproduce
Wear Ethereal wings, take them off, go try to fly with any other kind of flight item, be it creative or otherwise

**Comment by Saereth** [comment]
this should be fixed now on the server

**Comment by Cozary** [comment]
I thought I had fixed it. What version of the mod and forge are you using?

**Comment by Saereth** [comment]
We are currently on Nameless Trinkets-1.18.2-1.5.8.jar, I do see there is an update now but I didnt see anything about the wings in the patch notes, will udpate regardless but is the fix in 1.6.1 or still needs attention?

**Comment by Saereth** [comment]
ok the new update did fix this, thanks!
