### ISSUE TITLE
[1.18.2] Blindfold and Dark Nelumbo effects

### ISSUE THREAD

**Issue by JohnWeak1** [Cozary/Issue-Tracker#34]
the Blindfold and the dark Nelumbo effect stops for a fraction of a second while wearing them
(this is mostly a problem for the blindfold because mobs can detect you in that single tick)

**Comment by Cozary** [comment]
Mod and Forge version?

**Comment by Cozary** [comment]
Does it occur under certain circumstances or at all times?

**Comment by Wallano-pand** [comment]
hey, im going to ressurrect this bug again

it is actually a bug, mod 1.6.10/ forge 43.2.4

i didnt find if it has circumstances and what they are but it is frequent, what makes blindfold useless
sometimes it "blinks" more frequently and sometimes you just see enemies going for you even if you are invisible and 10 blocks away

**Comment by Cozary** [comment]
OK, I'll keep that in mind with the general rework I have in mind for the mod.
