### ISSUE TITLE
1.18.2 Creeper explodes normally

### ISSUE THREAD

**Issue by devjavu7** [Cozary/Issue-Tracker#36]
Version: 1.18.2 1.1.10

Creepers explode blocks around and do not turn them into ores. I did make sure to have stone blocks around.

**Comment by Cozary** [comment]
Are you saying that ore creepers explode like normal creepers? I'll see where I messed up.

**Comment by Cozary** [comment]
I just checked and everything works fine from my side. You blow up a "Coal Creeper" and it doesn't spawn ores around it? What version of Forge are you using? What other mods do you have installed?

**Comment by Burchard36** [comment]
https://www.curseforge.com/minecraft/mc-mods/creeper-confetti

Make sure this mod is not installed alongside this one. When both are installed together they result in this bug, cheers!
