### ISSUE TITLE
ColoredWater: Fluid translations to be more compatible

### ISSUE THREAD

**Issue by cech12** [Cozary/Issue-Tracker#37]
Mod: ColoredWater
Version: 1.19.2-1.3.3
Bug explanation:

Hey, I am the mod developer of [BucketLib](https://www.curseforge.com/minecraft/mc-mods/bucketlib) and [Ceramic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket). 

Your mod does not contain translations for the fluids. To be more compatible with other mods, I would recommend to add such translations. :)

Bug image:
![grafik](https://user-images.githubusercontent.com/16005054/193403721-eebac217-9ffe-4c15-bd2d-30a4b86cd59b.png)

**Comment by Cozary** [comment]
I didn't know "fluid_type" existed. I'll try to add it to the lang as soon as possible.

**Comment by Cozary** [comment]
I have uploaded an update to curseforge. Let me know if everything is ok.

**Comment by cech12** [comment]
Thanks for your fast answer and work! :)

As far as I can see, you added language keys which are named for example "fluid_type.colored_water.magenta_**water_fluid**", but the language key which is returned by your fluid types is "fluid_type.colored_water.magenta_**fluid**" (at the end "_water" is missing)

The method I use to get the language keys is `fluid.getFluidType().getDescription()`.
https://github.com/cech12/BucketLib/blob/1.19/src/main/java/cech12/bucketlib/api/item/UniversalBucketItem.java#L89

Maybe you can change your fluid types to return the fluid language key or you change the language keys. :)

**Comment by Cozary** [comment]
I'll change the lang and that's it. I'll take a little while to do it.

**Comment by Cozary** [comment]
I have uploaded an update to Curseforge. (should be available soon).

I think that this time I have put the "language keys" correctly. Let me know if all goes well. ^^

**Comment by cech12** [comment]
Now it is looking good! :) Thanks for your time! :)
