### ISSUE TITLE
Trinket is not destroyed when left-clicking on enchanting table

### ISSUE THREAD

**Issue by freevortex** [Cozary/Issue-Tracker#38]
Version 1.6.2; Forge 43.1.32

When left-clicking an extra trinket I do not want on an enchanting table, I get an unknown fragment, but the trinket is not destroyed. This means I can just keep clicking ad infinitum to get as many fragments as I want, and still retain the original trinket. I assume this is not intended behavior.

**Comment by Cozary** [comment]
Exactly, it's not intentional. I'll fix it.

**Comment by Cozary** [comment]
Fixed in the next version.

Changed the way to Recycle Trinkets. Now you have to right click on an Amethyst Block.

**Comment by drakray** [comment]
Right-clicking on an Amethyst Block seem to not destroy the trinket, but still give the Fragment

**Comment by Cozary** [comment]
I am very confused, I tested several times to verify that it worked. I will rewrite part of the code.

**Comment by Cozary** [comment]
I've uploaded a new update, if it still doesn't work I'll reopen the thread.
