### ISSUE TITLE
[1.18.2] Ethereal Wings Trinket permanently sets flight speed

### ISSUE THREAD

**Issue by jdnism** [Cozary/Issue-Tracker#39]
This was a previous issue, yet I am still receiving this problem on 'Nameless Trinkets-1.18.2-1.6.4.jar'
'Taking off ethereal wings does not return your flight speed values to normal, you maintain the same slow speed that the wings grant, even in creative.
Steps to reproduce
Wear Ethereal wings, take them off, go try to fly with any other kind of flight item, be it creative or otherwise'
Same issue as the one opened by user "Saereth" (https://github.com/Saereth).
Extra notes: I've tried getting rid of the item completely, and even uninstalling the mod, yet the slowness is still there.

**Comment by Cozary** [comment]
I fixed the main problem back in the day. Now is because it is not intended for you to unequip the item in creative. The flight value is only reset in survival. I'm going to do it so it can be done.

**Comment by Cozary** [comment]
I did an update that fixes the problem. It will be available in a short time.

**Comment by jdnism** [comment]
Firstly, thanks a heap for fixing it, it's all normal now, secondly, I get that it is probably unintended for me to take off a survival trinket in creative, but some people kinda like to mess around with mods. Thanks for your time :)

**Comment by Cozary** [comment]
Yes, it was also my fault for not considering it.
