### ISSUE TITLE
Floral Enchantment - No Class Defined Error

### ISSUE THREAD

**Issue by kreezxil** [Cozary/Issue-Tracker#4]
Crashes dedicated server with No Class Defined Error

server crash report: https://gist.github.com/92333197e0c1051a8d2af7dfb53925b4
server latest log: https://gist.github.com/48a5276ce3c7bfc43d3995a88f1f4b2b

Floral Enchantment 1.16.5-1.2.0
Forge: 36.2.8

**Comment by Cozary** [comment]
Hey! I have checked if there were any problems in multiplayer but it does not give me any crash. Are you using the latest version that forge recommends, 1.16.5-32.2.0? Can you give me a list of what mods you are using? It may be due to some incompatibility as I added a special rendering on the arms when holding the Large Pots.

**Comment by kreezxil** [comment]
Install World of Dragons II,
https://www.curseforge.com/minecraft/modpacks/world-of-dragons-ii
then update the mod. There is a server pack too. Update it there too. Enjoy
the crash.

I don't use the latest version of FORGE, i use the BLEEDING EDGE of Forge.
I have mods that are compiled against 36.2.8.

**Comment by Cozary** [comment]
I've done some research, and it seems to be an incompatibility with Obfuscate "https://www.curseforge.com/minecraft/mc-mods/obfuscate". I will try to bring a compatible version as soon as possible. Once it's done I'll put another message here with the new version and close the issue.

**Comment by Cozary** [comment]
"Fixed"
https://www.curseforge.com/minecraft/mc-mods/floral-enchantment/files/3514476

**Comment by kreezxil** [comment]
thank you. I'll update it in my back later today.

**Comment by kreezxil** [comment]
The update didn't work either.

## New crash report.
Crash report: https://gist.github.com/a091d9ab9c7805658b804741bcb45fdb
latest.log: https://gist.github.com/70d7257b29adf6926b0a80b8dbcd6695

I'll attach the server pack, you can run it by executing “start.bat” for Windows and “start.sh” for Linux.

https://drive.google.com/file/d/17Z7mpNKih7BzJGlDlx2pMhLELKNsXnBO/view?usp=drivesdk

**Comment by Cozary** [comment]
I uploaded another update, 1.2.2, which should fix the problem.

**Comment by kreezxil** [comment]
Awesome, thanks!
