### ISSUE TITLE
[BUG/SUGGESTION] Gods Crown

### ISSUE THREAD

**Issue by f0kx** [Cozary/Issue-Tracker#40]
Hello,

i play with a mod called scaling hearth...and your crown is 2x this scaling because of 120% stats! 
The problem is that after i relog all my hearth are to the max health of scaling hearths and after that your crown will take place and fill up all the other hearths! 
So the game cant remember the full hearthcontainer after relogging.

Is it possible to have all hearths after relogging? so i dont need to wait for replanshing all the extra hearths from your crown.(it takes a lot of food :P)

**Comment by Cozary** [comment]
It seems to be a small compatibility problem, I think it does not happen normally.
I'll see what I can do to fix it.
Version of the mod and forge?

**Comment by f0kx** [comment]
MINECRAFT: 1.19.2
FORGE: 43.1.43
Scaling Health: 1.19.2-7.0.0+6
Nameless Trinkets: 1.19.2-1.6.5

**Comment by Cozary** [comment]
Perfect, I'll see what the problem is and I'll try to fix it as soon as possible.

**Comment by Cozary** [comment]
I have been looking to see what was happening and it seems that the fix that I had added has stopped working in 1.19.x
I recommend you to use https://www.curseforge.com/minecraft/mc-mods/max-health-fix
