### ISSUE TITLE
[BUG]Miners Soul Trinket

### ISSUE THREAD

**Issue by f0kx** [Cozary/Issue-Tracker#41]
Hello,

the miners soul Trinket...if equipped denies the breaking of functional storage drawer of the functional drawer mod!
We tested it with and without the trinkets and it was the trinket not breaking it :D strange

Minecraft:1.19.2
Forge:43.1.43
Nameless Trinkets:1.6.6
Functional Storage:1.0.6

**Comment by Cozary** [comment]
I'll see what I can do and what the problem is.

**Comment by Saereth** [comment]
This is effecting some other mod blocks as well, notably evilcraft tanks
![image](https://user-images.githubusercontent.com/71052653/196770264-8f2dc280-981d-480f-856e-b3ccc1a583a2.gif)

**Comment by Smilelikejoker** [comment]
Can also confirm that the Miner's Soul is affecting Storage Drawers too.

Minecraft:1.19.2
Forge:43.1.1
Nameless Trinkets:1.6.6
StorageDrawers-1.19-11.1.2

SIDENOTE - Not sure if this is helpful, but switching to creative mode seems to give back some of the functionality when using Storage Drawers in combination with Carry On.  You can move them again.

**Comment by drakray** [comment]
Any leaves, vanilla Small Grass and Vine, Terraqueous Doodads and Supplementaries Cave Urns are also affected.
Breaking them drops nothing, then right-clicking the location make them reappear as if not broken.
Removing Miner's Soul allow normal breaking.

**Comment by Cozary** [comment]
The bug is supposed to be fixed and shouldn't cause any more problems. I have tested it with all the blocks that you have come to tell me and it already worked.

The new update is now available on Curseforge. If it has not been fully resolved, the issue will be reopened. 
Thanks for the report. ^^
