### ISSUE TITLE
[BUG] Floral Enchantment Crowns

### ISSUE THREAD

**Issue by SilveroGhost** [Cozary/Issue-Tracker#42]
Mod: Floral Enchantment [fabric]
Version: 1.18.2
Bug explanation: For some reason when using the flower crowns in this mod it creates a texture error that causes a purple box around the players head
Bug image
![2022-10-21_15 04 59](https://user-images.githubusercontent.com/116386270/197272719-fe1bda99-9136-45ec-ad80-f05155c5bbfb.png)

**Comment by Cozary** [comment]
Surely when I change the textures I leave behind the textures of the crowns. I'm sorry, I'll fix it as soon as possible.

**Comment by SilveroGhost** [comment]
Its alright things happen sometimes, take your time! And thank you, I really love this mod and I hope the issue isn't too difficult to fix
