### ISSUE TITLE
[compat issue] The Wooden Stick doesn't loose any of it's "shield"

### ISSUE THREAD

**Issue by Lucky-56** [Cozary/Issue-Tracker#43]
When I take damage the "shield" value doesn't drop also it instantly has it's cooldown.

actual issue: I basically have infinite overhealth

_I haven't checked which mod it conflicts with yet, as the modpack I'm playing with has more than 300 mods_

- **Forge:** 43.1.47
- **Mod:** 1.19.2-1.6.7
- **Mods causing the issue:** _haven't checked yet_

**Comment by Cozary** [comment]
Yes, I'm dumb and even if I made a complete change to the item that didn't get past the 1.19 branch. This weekend I'm going to fix a couple of problems so expect a new version soon.

**Comment by Lucky-56** [comment]
okay thanks in advance :3

**Comment by Cozary** [comment]
It should be fixed with the new version. ^^
