### ISSUE TITLE
Fertilizer causing Event#setCanceled() on PlayerTickEvent, while digging sand with plants on it

### ISSUE THREAD

**Issue by zsvan** [Cozary/Issue-Tracker#44]
I've searched for _fertilizer_ in issue history and didn't find anything so I hope I'm not duplicating submission because it's 1.16.5 version of the mod.

**Forge:** 1.16.5 - 36.2.21
**Mod version:** 1.1.3

**What happened:** I've landed on a desert and started to mass dig sand. Crashed with _Internal Server Error_ message. Log attached.
**Additional info:** Biome is _Desert Shrubland_, plants around were _Desert Sage_, _Dry Grass_ and _Faint Amaranth_ from _Project: Vibrant Journeys_ and _Astral Sorcery_ respectively. Fertilizer item also vanished after logging back in - although that may be also issue with _Squire's Bag_ adding additional trinket slot that needs to be populated again after logging out and back in? As in, item is taken off and has to be put back in. Crash may make it vanish.

[message.txt](https://github.com/Cozary/Issue-Tracker/files/9894407/message.txt)

**Comment by Cozary** [comment]
It should be fixed with the new version I just uploaded. I hope it doesn't keep giving error.
