### ISSUE TITLE
Server crashes when using Miner's Soul alongside Refined Storage Crafters

### ISSUE THREAD

**Issue by choombdev** [Cozary/Issue-Tracker#45]
On my server in my modpack, breaking a Crafter while having the Miner's Soul in my inventory crashed the entire server, I created a new instance and a singleplayer world with only Nameless Trinkets and Refined Storage and the issue persisted. 

While I didn't crash, the same errors were sent in the logs and the Crafter itself wouldn't break, it would just disappear and then re-appear.

Let me know if I should post this somewhere else or if there is a fix I can implement.
**Latest.log:** https://gist.github.com/choombdev/5608139514299e1d4fc2b632fc4741ea
**Modlist:**
curios-forge-1.18.2-5.0.7.1
Nameless Trinkets-1.18.2-1.6.8
refinedstorage-1.10.3

**Comment by Cozary** [comment]
I thought I fixed the problem. But it looks like I only fixed part of it.

**Comment by Cozary** [comment]
Fixed in the next update.
