### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by DMJessus** [Cozary/Issue-Tracker#46]
using Nameless Trinkets-1.19.2-1.6.9

here's the report on crashy: https://crashy.net/QHxKBLaFevPynFEtTpUn
 
basically, there's no entity loading for speed force? idk im not a code person. ^-^;;;;

**Comment by Cozary** [comment]
Weird bug, I'll see what I can do.

**Comment by Cozary** [comment]
Maybe it's a Forge version problem.
