### ISSUE TITLE
English Localization for Nameless Trinkets

### ISSUE THREAD

**Issue by jordan-moore** [Cozary/Issue-Tracker#47]
Hey I saw that on your wiki and in game some of the English language usage was a little rough.

I've attached a markdown file that could help the Wiki a bit and would happily help with in game localization as well if you'd like.

[Trinkets-Descriptions.md](https://github.com/Cozary/Issue-Tracker/files/9973122/Trinkets-Descriptions.md)

**Comment by Cozary** [comment]
Thank you! English is not my first language :P
I'll try to implement it when I have free time.
