### ISSUE TITLE
Flower Crowns Not Working in Floral Enchantment [Fabric]

### ISSUE THREAD

**Issue by Akane-N** [Cozary/Issue-Tracker#50]
Hello, I really love this mod but I noticed while testing it that the flower crowns don't work, they look like cute crowns in your inventory but the moment you put it on it just makes your whole head turn into a pink block, hopefully this can be fixed! keep up the good work ^~^

**Comment by Cozary** [comment]
Are you using the latest version? In v1.1.1 that problem was fixed.

**Comment by Akane-N** [comment]
I'm using 
Floral Enchantment-Fabric-1.19-1.1.0.jar
My server is 1.19 and i cant update it higher currently, is it not possible to fix it in 1.19? sorry to trouble you with this

**Comment by Cozary** [comment]
Fixed in next update.
