### ISSUE TITLE
Nameless Trinkets walking on fluids not working

### ISSUE THREAD

**Issue by penturt** [Cozary/Issue-Tracker#51]
Mod: Nameless Trinkets
Version: Nameless Trinkets-1.19.2-1.6.9.jar
Bug explanation: the walk on water and walk on lava trinkets do not seem to be working, i do have expandability-7.0.0 installed.

**Comment by TAKOMAN1** [comment]
I can confirm

**Comment by Cozary** [comment]
It is a known bug. I plan to fix it soon.

**Comment by Cozary** [comment]
Fixed
