### ISSUE TITLE
Ghast Eye's Extra Row of Hearts Resets After Re-Opening The World

### ISSUE THREAD

**Issue by TAKOMAN1** [Cozary/Issue-Tracker#52]
The Ghast Eye trinket gives you an extra row of hearts. If you leave the world with more than 10 hearts and enter it again, the game takes a second to load the trinket after the world was loaded, and forgets all the hearts that you had.

Minecraft version – 1.19.2
Latest mod version.

**Comment by Cozary** [comment]
It's minecraft stuff.
