### ISSUE TITLE
[Bug?] Reforger don't repair equipped armor

### ISSUE THREAD

**Issue by drakray** [Cozary/Issue-Tracker#53]
Equipped Armor seems to not be repaired by the Reforger.
Putting the armor in the inventory or hotbar works as expected.
I have not tested if [Cosmetic Armor Slot](if Cosmetic Armor Slot) are repaired though, and Curio config are modified to have more slots(don't know if it could be a slot number issue?)

Minecraft 1.18.2
Forge 40.1.92
NamelessTrinket 1.6.9
Buncha Other Mods

**Comment by Cozary** [comment]
It's not a bug, it's intentional. Only what is in inventory is repaired.
