### ISSUE TITLE
[Nameless Trinkets] Adding a way to completely disable a trinket or/and remove it from the Mysterious Fragment's Random Trinket

### ISSUE THREAD

**Issue by choombdev** [Cozary/Issue-Tracker#57]
Title!

Let me know if it already exists and I missed it, I've disabled a few trinkets from spawning in chests but they still spawn through the Mysterious Trinket item.

**Comment by Cozary** [comment]
One thing does not affect the other. In a future update I plan to add a "deactivation" of trinkets. They can be obtained but they will not work.
