### ISSUE TITLE
[1.18.2] Crash: Mod loading error has occurred

### ISSUE THREAD

**Issue by DeshiDesu** [Cozary/Issue-Tracker#58]
Nameless Trinkets-1.18.2-1.6.11-Beta.jar
Forge 40.2.1

Crash Report:
 > [crash-2023-04-16_23.02.16-fml.txt](https://github.com/Cozary/Issue-Tracker/files/11245820/crash-2023-04-16_23.02.16-fml.txt)

**Comment by Cozary** [comment]
fixed
