### ISSUE TITLE
[1.18.2] Crash: Invalid null NBT value with key rageEntity

### ISSUE THREAD

**Issue by DeshiDesu** [Cozary/Issue-Tracker#59]
Nameless Trinkets-1.18.2-1.6.11-Beta-2

Crash:
> [crash-2023-04-19_00.48.39-server.txt](https://github.com/Cozary/Issue-Tracker/files/11268653/crash-2023-04-19_00.48.39-server.txt)

**Comment by Cozary** [comment]
fixed thx ^^
