### ISSUE TITLE
Bush Replace

### ISSUE THREAD

**Issue by Modeeves** [Cozary/Issue-Tracker#6]
I don't think it's a bug or anything like that, but normally, when I right-click any of the bush types, it will pop out the vines first then the modded flowers, right? However, if I am holding a flower on either hand then right-clicked the bush with no vines or flower, the flower that I am holding will be planted on that spot then replace the bush block, therefore, deleting or banishing (I don't know what's the right term) the bush block even if I destroyed the flower I accidentally planted while right-clicking.

I think that's kinda inconvenient. Is there a way to fix that in the configs or something?

**Comment by Cozary** [comment]
Yes, it is a bug. It is not intentional so I will try to fix it.

**Comment by Cozary** [comment]
It was my mistake with the Material assigned to the block. It has been changed and a new version of the mod is already being uploaded.
