### ISSUE TITLE
Ore Creepers has no Compat with All the Ores 1.19.2

### ISSUE THREAD

**Issue by Xaeive** [Cozary/Issue-Tracker#61]
1.19 Ore Creeper does not have compatibility with All the Ores? I've tried all versions of 1.19.2.

**Comment by Cozary** [comment]
It does but it was disabled. When I updated Ore Creepers to 1.19, All the Ores was not updated yet and it was something that dragged.

Since I have had very little free time in the last few months, I have not been able to re-enable it. I intend to, when I enable it I will close this thread.

**Comment by Cozary** [comment]
Although I'm not a big fan, I'm going to stop giving support to the various compatibility that there was. ATO, for example, has a version for 1.19.2 but not for 1.19.4. I can't keep up with the updates.
