### ISSUE TITLE
Trinkets not considered as such

### ISSUE THREAD

**Issue by realslimicee** [Cozary/Issue-Tracker#62]
Mod: Nameless Trinkets-1.18.2-1.6.11-Beta-3.jar

Version: 1.18.2, being played in conjunction with the Vault Hunters 3 mod.

Bug explanation: Any of the Nameless Trinkets that are considered a trinket have lost said tag, and are now just items incapable of being equipped. Those for the head, body, etc. still function as they should. 

Bug image: https://imgur.com/a/cBbpdKQ

Crash: No crash has occurred due to this.

**Comment by Cozary** [comment]
Sorry for the inconvenience but you are using a Beta. Try v1.7.0 which should fix most of the problems that Beta had.

**Comment by realslimicee** [comment]
Switched from the beta to 1.7.0, but the same issue persists. I'm starting to wonder if it's just something with Vault Hunters that's messing with the trinkets.

**Comment by Cozary** [comment]
In the end it seems to be a different problem than what I thought, sorry for the inconvenience. In v1.7.2 everything should be fixed.

**Comment by realslimicee** [comment]
Ah, thanks for getting back to me. I'll try out the new version, then.
