### ISSUE TITLE
[1.19.2] Nelumbo Not Working in Nameless Trinkets-1.19.2-1.7.2

### ISSUE THREAD

**Issue by carlstrax** [Cozary/Issue-Tracker#64]
-Forge 43.2.13
-Nameless Trinkets-1.19.2-1.7.2.jar

Nelumbo is not working on the latest version (Nameless Trinkets-**1.19.2-1.7.2.jar**) for me. I have to go back to this version to get Nelumbo to work again (Nameless Trinkets-**1.19.2-1.6.11.jar**). 
I have **ExpandAbility** installed.

**Comment by Cozary** [comment]
They are always giving me trouble. Maybe I did something wrong when I was deleting code so now Expandability is required. I'll try to fix it this week.

**Comment by Cozary** [comment]
It is fixed but the version that brings the fix will take time to come out.
