### ISSUE TITLE
Large pot causing crashes when placed

### ISSUE THREAD

**Issue by cnmhqwerty** [Cozary/Issue-Tracker#66]
Exit code: -1

"The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to up on Block{floralench:large_pot}, it is not an allowed value"

**Comment by cnmhqwerty** [comment]
Running fabric 1.20 and the crash only occurs on some blocks but not others with no distinguishable pattern/logic

**Comment by Cozary** [comment]
The problem is supposed to be fixed. In the new v1.1.4
