### ISSUE TITLE
Loading crash

### ISSUE THREAD

**Issue by castilio20** [Cozary/Issue-Tracker#67]
It seems the game crash with the mod
[crash-2023-07-31_09.23.32-client.txt](https://github.com/Cozary/Issue-Tracker/files/12212037/crash-2023-07-31_09.23.32-client.txt)
[latest.log](https://github.com/Cozary/Issue-Tracker/files/12212040/latest.log)
 
the log says about your mod and the crashlog says about another mod (gregtech) so i asume some kind of compat issue
Mod:1.7.4
Version:1.20.1
Forge:47.1.3

**Comment by Cozary** [comment]
Do you have the ExpandAbility mod installed? Because it is a required dependency.

**Comment by castilio20** [comment]
yeah didnt had that ups my bad a little wierd that the log didnt sayd anything that you need that mod
