### ISSUE TITLE
Tinted Campfires [Suggestion]: Copy over entire blockstate or at least lit blockstate when placing tinted campfires

### ISSUE THREAD

**Issue by Xaidee** [Cozary/Issue-Tracker#69]
Noticed its a bit weird when dying an unlit campfire that it suddenly lights itself, I noticed it currently atleast copies over the direction value when replacing campfires. If the tinted campfires extends the base campfire class it should be safe to just copy over the entire campfire blockstate over to the placed campfires rather than setting just copying the direction value. It'd also be nice if items cooking on the campfire stayed there as well but that might be a little harder since that would require transfering the BlockEntity data which is a little more complicated. Thank-you appreciate your work ^-^

**Comment by Cozary** [comment]
You're right, there are several things I can modify in the code to make it better. I was thinking of doing an almost complete rework of the code to make it more accessible to do compatability with other mods that add colors. When I do that, I will also do what you tell me.
