### ISSUE TITLE
Colored Water Buckets not actually setting down Colored Water, just normal water

### ISSUE THREAD

**Issue by NighthowlerStudios** [Cozary/Issue-Tracker#7]
Possibly a mod that changes water might be incompatible and overriding the color render.  I'm unable to check if the water block id itself is correct.

I'm using a modpack with many mods.  However mods that I do know can affect water color is Quark, Better Biome Blend, Oh The Biome's You'll Go, Ars Nouveau, The Undergarden and Optifine

**Comment by Cozary** [comment]
I will look at what may be the problem that causes it.

**Comment by Cozary** [comment]
Well, the first time I found the problem. Optifine is not supported, I suppose it is because of the changes it makes to the rendering. There are other mods dedicated to optimization, I recommend using them.

**Comment by NighthowlerStudios** [comment]
sadly my pack is not stable with them (sodium reforged etc).  looks like I won't be using this mod :/ thanks for trying I guess.

**Comment by NighthowlerStudios** [comment]
you *should* be able to stop optifine from overriding it by making sure your fluid is marked as a modded fluid (using the forge api) and isn't just a straight up inheritance of the Water class.  this would explain why modded fluids from other mods (for example Ice and Fire's special fluids, or BOP's Blood fluid) don't break in this way.

**Comment by NighthowlerStudios** [comment]
I suggest at least attempting what I have suggested before straight up abandoning this issue.

**Comment by NighthowlerStudios** [comment]
yo, I understand you might not like it but a bunch of forge devs I am friends with agree with me that the issue might be you arent' registering the fluid blocks as Modded fluid which is why it's misbehaving.  it would be appreciated if you reopened this issue and attempted such fix.

I tried Magnesium as well and it breaks it too, that is our evidence you didn't register them properly.

**Comment by Cozary** [comment]
Well, if it's my fault I'll try to fix it then. ^^

**Comment by NighthowlerStudios** [comment]
Thank you so much for reopening this.  seeing that magnesium breaks it the same way does give a hint it might be a problem with your code.

we'll be here to help you if you need.

**Comment by Cozary** [comment]
I've been doing some research and it seems to be an Optifine thing. Liquids are correctly registered via Forge. I guess it's because the liquids are hardcoded. I've tried a couple of things but they don't work. Here you can see that it is a problem that has not been fixed for quite some time: https://github.com/sp614x/optifine/issues/3226#issue-548737003

**Comment by NighthowlerStudios** [comment]
yeah we did some research on our end as well.  sorry for the wild goose chase.
