### ISSUE TITLE
Can't Place Blocks on Top of Water

### ISSUE THREAD

**Issue by 123FLO321** [Cozary/Issue-Tracker#70]
Mod: Colored Water
Version: 1.20.1 1.3.7 (Forge 47.1.44)
Bug explanation: Unable to place any blocks in colored water

**Comment by Cozary** [comment]
Ok, I just tried it and I have no idea why it happens. And it only happens from 1.20.x onwards. :/

**Comment by Cozary** [comment]
I found the problem. I'll try to fix it asap
