### ISSUE TITLE
[1.18.2 forge] Nameless Trinkets - Slik Touch + Fortune game break

### ISSUE THREAD

**Issue by Christofmeg** [Cozary/Issue-Tracker#72]
Mod: Nameless Trinkets
Version: Nameless Trinkets-1.18.2-1.7.4

If a player mines an ore with slik touch while wearing **Four Leaf Clover** or **Miner's Soul** they get both the ore they slik touched and any drops the ore would have dropped.

This also applies to bookshelves.

Suggestion please prevent these trinkets from activating when breaking blocks with silk touch. 

This is easily game breaking in modpacks.

**Comment by Cozary** [comment]
Wow, that's not intentional. You can have infinite Ores that way. I will try to solve it as soon as possible. Thanks ^^

**Comment by Cozary** [comment]
I just realized that Four Leaf Clover has nothing to do with what you're talking about. Since it only affects entities, not blocks.

**Comment by Cozary** [comment]
Fixed in the latest version, I will release the fix to the other versions little by little.
