### ISSUE TITLE
Nameless Trinkets 1.7.4 (1.18.2) - Rage Mind trinket crashes the game

### ISSUE THREAD

**Issue by RatseerOfRattesse** [Cozary/Issue-Tracker#73]
I was playing with Nameless Trinkets and a ton of other mods. While fighting mobs in a cave the game froze and crashed. After reviewing the crash report, it looks like the Rage Mind curio was trying to apply the glowing effect to an arrow and the game subsequently crashed because of it.

Crash Report:
[crash-2023-08-25_16.04.24-server.txt](https://github.com/Cozary/Issue-Tracker/files/12444184/crash-2023-08-25_16.04.24-server.txt)

**Comment by Cozary** [comment]
Yes, it is a bug that has been fixed in later versions (+1.19). I totally forgot I made the change for 1.18 as well, I'll release the fix as soon as possible.

**Comment by RatseerOfRattesse** [comment]
Thanks for the confirmation.

**Comment by Cozary** [comment]
In the next version it will be fixed.
