### ISSUE TITLE
[1.20.1] This is a weird one

### ISSUE THREAD

**Issue by Crankonator** [Cozary/Issue-Tracker#79]
Hello, i come to report something weird i noticed with your mod.
While wearing the god crown, the game seems to think my damage boost is coming from the vampire blood trinket
(note that the god crown boost is set to 69%)
![image](https://github.com/Cozary/Issue-Tracker/assets/108573834/169f9d82-dc66-4c35-851e-affca9b2db18)
![image](https://github.com/Cozary/Issue-Tracker/assets/108573834/560a807e-7e22-4bdf-9f88-7dfd49bad761)

**Comment by Cozary** [comment]
The game is not thinking that the damage is coming from somewhere else.  It's just that I put the names wrong x)

Luckily it is a minor problem that should not affect anything.

**Comment by Crankonator** [comment]
Ahh i see haha

**Comment by Cozary** [comment]
It has been fixed.
