### ISSUE TITLE
1.18 Trinkets odd behavious 

### ISSUE THREAD

**Issue by ffuentesm** [Cozary/Issue-Tracker#8]
Mod: Nameless Trinkets
Version: Nameless Trinkets-1.18.1-1.1.1.jar
Bug explanation: By now I found 2 bugs 
Experimental Battery trinket suddenly kept giving me XP nonstop until I removed the trinket. I got to lv 40000 out of nowhere after entering a new village. 
Sleeping Pills can't be removed. I am in Day Time, in the overworld, but I can't remove the trinket from the Curious slot.

**Comment by Cozary** [comment]
Did you do something specific with the Experience Battery? I mean if something happened like receiving an achievement, or did you receive experience just upon entering the village?

The only thing that the object does is give you extra experience when leveling up and that's it. Maybe you modified the "Experience Multiplier" in the object's configuration files? The base value is 0.03 and it is a very sensitive value. Climbing it up can cause it to get out of control.

Do you remember what level you were when it happened?

That Sleeping Pills cannot be removed is my fault, I will have made a mistake when porting the mod to 1.18.

**Comment by ffuentesm** [comment]
It was upon entering the village. 

I was somewhere close to lv 30 at the time. 
I do not recall gaining achievements. But I might have gained xp?
And I did not touch the config file.

**Comment by Cozary** [comment]
I will do several tests, to see if I find the problem and I will try to bring a solution as soon as possible.

**Comment by ffuentesm** [comment]
ok, so I tried the Experimental battery again, and I am strangely gaining levels at random times.
I am literally breaking grass and I got levels. I am jumping around and I am gaining 3 levels.

**Comment by ffuentesm** [comment]
Also, would be possible to remove the "fire hit" when the blaze knuckles are equipped? 
It gives fire immunity, so why do we still get the hit animation?

**Comment by Cozary** [comment]
I have been testing and the Experience Battery gives you infinite levels reached certain levels so I have to cap it, but you just told me that you get experience randomly, something that should not be possible. Are you playing with a modpack? If so, could you tell me?

About the "fire hit" it was already thought to be changed and will be in a future update.

**Comment by ffuentesm** [comment]
Could you remove the Hit taken from fall damage in Moon stone?

**Comment by Cozary** [comment]
Yeah, I can do that too.

**Comment by zsvan** [comment]
> Did you do something specific with the Experience Battery? I mean if something happened like receiving an achievement, or did you receive experience just upon entering the village?
> 
> The only thing that the object does is give you extra experience when leveling up and that's it. Maybe you modified the "Experience Multiplier" in the object's configuration files? The base value is 0.03 and it is a very sensitive value. Climbing it up can cause it to get out of control.
> 
> Do you remember what level you were when it happened?
> 
> That Sleeping Pills cannot be removed is my fault, I will have made a mistake when porting the mod to 1.18.

Hello. Not being able to remove Sleeping Pills issue is present in version _Nameless+Trinkets-1.16.5-1.1.3_ as well. Would it be possible to release a fixed jar for this MC version?

**Comment by Cozary** [comment]
Yes, of course. In a "undetermined time" it will be done.

**Comment by Cozary** [comment]
Done
