### ISSUE TITLE
[1.20.1] Permanently slow flying speed in creative w/ ethereal wings

### ISSUE THREAD

**Issue by YurikoTsuyuki** [Cozary/Issue-Tracker#84]
Taking off ethereal wings does not return your flight speed values to normal, you maintain the same slow speed that the wings grant, even in creative

Steps to reproduce
Wear Ethereal wings, take them off, go try to fly with any other kind of flight item, be it creative or otherwise

**Comment by Cozary** [comment]
It _should_ be fixed by now (the update will take some time)👍
