### ISSUE TITLE
Can no longer include the mod in modpacks?

### ISSUE THREAD

**Issue by spiritedsnowcat** [Cozary/Issue-Tracker#9]
Hi there,

I went to update my modpack for my home server, and I'm now getting the following error message when uploading to curseforge:

```
 Notes:
The following files belong to CurseForge-hosted projects, and should therefore not be added directly to zip files:

    overrides/mods/Floral Enchantment-1.18.1-1.3.0.jar


These files should, instead, be referenced in the manifest.json file generated by the Twitch Desktop App during a profile export.

If you have any questions please contact our support team https://support.curseforge.com. 
```

Am I no longer permitted to include the mod in my modpack? 

Thanks,
Spirited

**Comment by spiritedsnowcat** [comment]
Hm, it does only seem to be this mod that causes the issue. Removing the mod allows me to upload new versions of the modpack. 😕

**Comment by Cozary** [comment]
![image](https://user-images.githubusercontent.com/69899934/147364371-9e061c61-59ec-43c9-894f-e01a0b03b71a.png)
That's weird... Because at no point have I revoked the permission to be able to use them in modpacks.

**Comment by Cozary** [comment]
I have updated the permission, if it doesn't work let me know.

**Comment by Cozary** [comment]
I have done some research and have seen that it is a relatively common problem. If you do not find a solution to the problem, I suggest you contact https://support.curseforge.com
